spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/printshop?useUnicode=true&characterEncoding=utf8
    username: Ninh
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate    # dev có th? dùng update
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
