spring:
  datasource:
    url: jdbc:mysql://localhost:3306/printshop?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update   # dev dùng update cho dễ chạy
server:
  port: 8080
