server:
<<<<<<< HEAD
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/printshop
    username: Ninh
=======
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/printshop
    username: root
>>>>>>> huynhtannha-dev
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
<<<<<<< HEAD
      ddl-auto: validate
=======
      ddl-auto: update
>>>>>>> huynhtannha-dev
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
<<<<<<< HEAD
=======
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
>>>>>>> huynhtannha-dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
<<<<<<< HEAD
=======
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:huynhtannha2003@gmail.com}
    password: ${MAIL_PASSWORD:cgah urjw psal rrvk}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
>>>>>>> huynhtannha-dev

file:
  upload-dir: ./uploads

jwt:
  secret: 123456789101234567891012345678910123456789101234567891012345678910
  expiration: 86400000 # 24 hours in milliseconds
  refresh-token:
    expiration: 604800000 # 7 days in milliseconds
<<<<<<< HEAD
=======

app:
  email:
    from: ${MAIL_FROM:noreply@printshop.com}
  otp:
    fallback: ${OTP_FALLBACK:true}  # Set to true to use in-memory OTP (no Redis needed)
>>>>>>> huynhtannha-dev
